version: '3.8'

services:
  api:
    # image: node:18
    build: .
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    command: npm run api
    depends_on:
      - db
    links:
      - db

  db:
    image: mongo:latest
    restart: always
    ports:
      - '3001:27017'
    volumes:
      - ./data/db:/data/db
